---
language: generic

services:
  - docker

install:
    # generate dummy SSH key pair
  - ssh-keygen -t ed25519 -f $HOME/.ssh/id_ed25519 -N ''
    # Docker image
  - docker build -t sshd-s6-docker --build-arg USER_SSH_PUBKEY="$(cat $HOME/.ssh/id_ed25519.pub)" .

script:
  - echo 'CONTAINER_ID="$(docker run -d sshd-s6-docker)"' > .env
  - echo 'CONTAINER_IPADDR="$(docker container inspect --format '"'"'{{ .NetworkSettings.IPAddress }}'"'"' "$CONTAINER_ID")"' >> .env
  - source .env
  - echo '+ waiting for OpenSSH server availability';
    while ! nc -z -w1 "$CONTAINER_IPADDR" 22; do echo '.'; sleep .5; done
  - ssh -o StrictHostKeyChecking=no ansible@"$CONTAINER_IPADDR" id
  - docker logs "$CONTAINER_ID"
  - docker stop "$CONTAINER_ID"
  - docker rm -v "$CONTAINER_ID"
